services:
  - type: web
    name: expense-tracker-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: nozomi.proxy.rlwy.net
      - key: DB_PORT
        value: 10370
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: cabhoPkANrMJJfONeRwFDbWsWFfxmInD
